Bug Fix: Date spine timestamp Error
fivetran/dbt_sage_intacct pull request #24
Opened 2024-07-30 03:58 UTC by fivetran-avinash

## PR Overview
**This PR will address the following Issue/Feature:** [#23]

**This PR will result in the following new package version:** 0.14.1

No fields were changed in this update, just the behavior of the spine for empty general ledger models. 

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

# Bug Fixes
- Updated the `int_sage_intacct__general_ledger_date_spine` model to accommodate for the cases when the compiled `sage_intacct__general_ledger` model has no transactions. In this case, the model now defaults to a range of one-month from the current date.

## Under The Hood
- Updated the structure of the `int_sage_intacct__general_ledger_date_spine` model for improved performance and maintainability.
- Added `flags.WHICH in ('run', 'build')` as a condition in `int_sage_intacct__general_ledger_date_spine` to prevent call statements from querying the staging models during a `dbt compile`.
- Addition of integrity and consistency validation tests within integration tests for the `sage_intacct__general_ledger` and `sage_intacct__general_ledger_by_period` model.

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt run –full-refresh && dbt test
- [NA] dbt run (if incremental models are present)

Before marking this PR as "ready for review" the following have been applied:
- [x] The appropriate issue has been linked, tagged, and properly assigned.
- [ ] All necessary documentation and version upgrades have been applied.
    
- [ ] docs were regenerated (unless this PR does not include any code or yml updates).
- [ ] BuildKite integration tests are passing.
- [ ] Detailed validation steps have been provided below.

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-07-30 19:49 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Updated the `int_sage_intacct__general_ledger_date_spine` model to accommodate for the cases when the compiled `sage_intacct__general_ledger` model has no transactions. In this case, the model now
```suggestion
- Updated the `int_sage_intacct__general_ledger_date_spine` model to accommodate for the cases when the compiled `sage_intacct__general_ledger` model has no transactions. In this case, the model now defaults to a range of one month leading up to the current date.
```

2024-07-30 19:50 UTC, fivetran-reneeli reviewed
Looks good just to set it as a breaking change!

2024-07-31 14:30 UTC, fivetran-reneeli approved these changes
lgtm

2024-08-01 15:00 UTC, fivetran-joemarkiewicz requested changes
@fivetran-avinash thanks for your work on this PR. It's looking great, I just have a few small notes before approval. Let me know if you want to sync on any of my notes.

2024-08-01 16:10 UTC, fivetran-avinash commented on integration_tests/tests/integrity/integrity_general_ledger_by_period.sql
> +)
@fivetran-joemarkiewicz Makes sense. Just checking--this last line is supposed to be the `sage_intacct__general_ledger_by_period`?

2024-08-01 16:27 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/integrity/integrity_general_ledger_by_period.sql
> +)
Ah yes, copy/paste error on my part

2024-08-01 20:28 UTC, fivetran-avinash commented on integration_tests/tests/integrity/integrity_general_ledger_by_period.sql
> +)
Updated

2024-08-01 20:28 UTC, fivetran-avinash commented on CHANGELOG.md
> +    - This is a breaking change, as this will change what transaction records of `sage_intacct__general_ledger_by_period` end up in our final models.
Updated

2024-08-01 20:28 UTC, fivetran-avinash commented
> @fivetran-avinash thanks for your work on this PR. It's looking great, I just have a few small notes before approval. Let me know if you want to sync on any of my notes.

@fivetran-joemarkiewicz This is ready for re-review.

2024-08-01 20:33 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-08-01 20:37 UTC, merged